### ISSUE TITLE
Can i build function classifier using code-transformer

### ISSUE THREAD

**Issue by nbdfls** [danielzuegner/code-transformer#16]
Hi,
I would like to build a method/function classifier using code-transformer, the labels are going to be 0,1,2,..9,

Could i get some suggestions on how to build it?

Any guidelines would be hugely appreciated! :D

**Comment by vthost** [comment]
I am currently trying the same and add the classes as label instead of the function name, setting `separate_label_vocabulary` to `True` and `num_subtokens_output` to `1`. But maybe the authors have a better solution :)

**Comment by danielzuegner** [comment]
Yes, that should be a fairly direct way to achieve what you want. Closing this, feel free to reopen in case you have follow-up questions.

**Comment by tobias-kirschstein** [comment]
Cool idea to use the Code Transformer for method classification. A few remarks:

- **Preprocessing**: When using the separate label vocabulary approach you will have to adapt how the output vocabulary is populated (by default it is filled with all word tokens that appear in method names). This is handled in the [preprocess-1.py](https://github.com/danielzuegner/code-transformer/blob/main/code_transformer/experiments/preprocessing/preprocess-1.py) (Counting of tokens) and in [preprocess-2.py](https://github.com/danielzuegner/code-transformer/blob/main/code_transformer/experiments/preprocessing/preprocess-2.py) (Collecting the most common tokens into a vocabulary). If you want to avoid running the preprocessing pipeline to generate your own dataset, it should also be possible to add your classification output vocabulary to the already existing vocabularies (the `vocabularies.p` file is just a pickled 3- or 4-tuple of `Vocabulary` objects).
- **Model Input**: Obviously, you also need to change how the preprocessed methods are fed into the model. The standard dataset view we used for the [Code Summarization](https://github.com/danielzuegner/code-transformer/blob/main/code_transformer/preprocessing/dataset/code_summarization.py) task masks the method name, which you probably don't want.
- **Model**: Furthermore, by default, the training script uses an `Code Transformer` encoder together with a regular Transformer Decoder. For Method Classification having a simple linear layer in the end instead of the Decoder might be better.

**Comment by vthost** [comment]
Thank you, this is helpful!
