### ISSUE TITLE
Using code-transformer on c++ code

### ISSUE THREAD

**Issue by bfdyoy** [danielzuegner/code-transformer#20]
Hello, I'm currently working on clustering some competitive programming code based on the algorithm used and I would like to know if I could use your model to predict method's names. Couldn't find anything cpp related.

Thanks ! Have a good day !

**Comment by tobias-kirschstein** [comment]
Hi, 

thank you for your interest in the `Code Transformer`.
The model itself is language-agnostic and thus is applicable to C++.
However, we did not perform any experiments for that language, i.e., the preprocessing is not adapted to it.
The crucial part is the parsing of ASTs from C++ source code. 
As the AST parser that we used for our experiments, [semantic](https://github.com/github/semantic), does not currently support C++, one would have to integrate a separate C++ AST parser into the preprocessing for the Code Transformer (similar to how we did it for Java, which is also not fully supported by semantic). 
This is certainly possible, but requires some work.
First, you need to employ a C++ AST Parser to get syntactic information out of C++ code snippets. I guess, [cppast](https://github.com/foonathan/cppast) could work.
The AST Parser should meet the following requirements:
 * Every node should have a node type
 * Every node should point to the original source code lines that it refers to. E.g., for an IFStatement node we need the exact lines where this if statement appears in the source code file

Then, to reuse the remaining of our preprocessing pipeline (i.e., the calculation of graph distances), the AST needs to be provided in a specific format. To be precise, each code snippet has to be processed into a `CTStage1Sample` (see [source](https://github.com/danielzuegner/code-transformer/blob/a4b9af4e07f3d9f0ec36facd7962b6a47a8f2412/code_transformer/preprocessing/pipeline/stage1.py#L131)).
Basically, the following fields have to be provided:
 * `tokens`: list containing the result of tokenizing the source code snippet
 * `ast`: The AST obtained from using a C++ AST parser
 * `token_mapping`: maps each token to a node in the AST (that's why we need the lines in the original source code)
 * `stripped_code_snippet`: Code snippet with comments etc. removed
 * `func_name`: The name of the actual method

The AST itself is represented in a simple graph format (see [ASTGraph ](https://github.com/danielzuegner/code-transformer/blob/a4b9af4e07f3d9f0ec36facd7962b6a47a8f2412/code_transformer/preprocessing/graph/ast.py#L15) and [ASTNode](https://github.com/danielzuegner/code-transformer/blob/a4b9af4e07f3d9f0ec36facd7962b6a47a8f2412/code_transformer/preprocessing/graph/ast.py#L144)).
This should be sufficient to use the `CodeTransformer` on C++ methods.

I hope this helps. 
If you do end up integrating a C++ AST parser into the preprocessing pipeline, do come back to us. It would be great to add the integration to the repository in this case ;)

Best, 
Tobias
